### ISSUE TITLE
Provide way to use hostPath instead of PV

### ISSUE THREAD

**Issue by mattfysh** [bytewax/helm-charts#30]
I recently worked with redpanda's helm chart, and found they offer two ways to specify storage - you can choose either hostPath or the default PV

https://github.com/redpanda-data/helm-charts/blob/10ff7ea15167a595c99e029a0fed8bc0e880494b/charts/redpanda/values.yaml#L412-L437

Having a hostPath option is useful for local development where you want to avoid managing PV+PVC lifecycles

**Comment by miccioest** [comment]
That's a good idea, thanks for your contribution @mattfysh 

We'll add the hostPath option soon.

**Comment by miccioest** [comment]
HostPath was added in Helm Chart version `0.8.1`

**Comment by mattfysh** [comment]
Thanks @miccioest 🙌  this will make local dev a lot easier!
